<a href="https://colab.research.google.com/github/manvi-smaran/1024160111_UCS420_CC_Assignments/blob/main/1024160111_A6_UCS420.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q1(a-e): Sensor readings, vectorization and Boolean indexing

import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

c = temperature + 2
f = (9/5) * c + 32
x = c[c > 32]
n = np.sum(c > 32)

print("Corrected Celsius:", c)
print("Fahrenheit:", f)
print("Readings > 32°C:", x)
print("Count > 32°C:", n)

print("\nVectorization applies operations to the complete array at once,")
print("which is generally faster and simpler than explicitly using a loop.")
print("Boolean indexing directly selects elements satisfying a condition.")

Corrected Celsius: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings > 32°C: [33 37 40 35 42]
Count > 32°C: 5

Vectorization applies operations to the complete array at once,
which is generally faster and simpler than explicitly using a loop.
Boolean indexing directly selects elements satisfying a condition.


In [ ]:
# Q2(a-f): Analyze daily step data using NumPy

steps = np.array([[5000, 6200, 7100],
                  [8000, 7500, 9000],
                  [4500, 5100, 4800],
                  [9000, 8500, 9500]])

print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))
print("Total for each day:", np.sum(steps, axis=0))
print("Total for each user:", np.sum(steps, axis=1))

p = np.unravel_index(np.argmax(steps), steps.shape)
print("Maximum position (user, day):", p)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total for each day: [26500 27300 30400]
Total for each user: [18300 24500 14400 27000]
Maximum position (user, day): (np.int64(3), np.int64(2))


In [ ]:
# Q3(a-j): NumPy slicing, copying, reshaping, flattening and array properties

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

copy_a = original[1:5].copy()
copy_a[0] = 500

print("Original after modifying copy:", original)
print("Copied array:", copy_a)

a = np.arange(1, 13).reshape(3, 4)

print("\nMatrix:\n", a)
print("First row:", a[0])
print("Last row:", a[-1])
print("Second column:", a[:, 1])
print("Rows 1-2, columns 2-3:\n", a[1:3, 2:4])

flat = a.flatten()
rav = a.ravel()

rav[0] = 100
print("\nAfter modifying ravel:")
print("Original:\n", a)
print("Ravel:", rav)

flat[1] = 200
print("\nAfter modifying flatten:")
print("Original:\n", a)
print("Flatten:", flat)

print("\nShape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data type:", a.dtype)

Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copy: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, columns 2-3:
 [[ 7  8]
 [11 12]]

After modifying ravel:
Original:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]

After modifying flatten:
Original:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flatten: [  1 200   3   4   5   6   7   8   9  10  11  12]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [ ]:
# Q4(a-g): Matrix operations, OLS coefficients and prediction

X = np.array([[6, 70, 3],
              [5, 50, 6],
              [8, 80, 2],
              [4, 30, 8]])

y = np.array([40, 65, 30, 85])

print("Shape:", X.shape)
print("Dimensions:", X.ndim)

xt = X.T
print("\nX.T:\n", xt)

print("\nX.T @ X:\n", xt @ X)

b = np.linalg.inv(xt @ X) @ xt @ y
print("\nCoefficients:", b)

new_user = np.array([5, 40, 7])
pred = new_user @ b

print("\nPredicted assistance score:", pred)

print("\nThe coefficients represent the estimated effect of")
print("sleep hours, activity level and stress level on the assistance score.")

Shape: (4, 3)
Dimensions: 2

X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Coefficients: [-0.15921454  0.14083853 10.06302242]

Predicted assistance score: 75.27862544779117

The coefficients represent the estimated effect of
sleep hours, activity level and stress level on the assistance score.
