<a href="https://colab.research.google.com/github/manvi-smaran/1024160111_UCS420_CC_Assignments/blob/main/1024160111_A5_VemulaManviSmaran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr=np.array([1,2,4,4,5,5,5])
arr.dtype

dtype('int64')

In [ ]:
arr+2

array([3, 4, 6, 6, 7, 7, 7])

In [ ]:
arr*3

array([ 3,  6, 12, 12, 15, 15, 15])

In [ ]:
arr/2

array([0.5, 1. , 2. , 2. , 2.5, 2.5, 2.5])

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr[::-1]

array([5, 4, 6, 3, 2, 1])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
values,counts=np.unique(x,return_counts=True)
print(values)
print(counts)
print(np.argmax(counts))

[1 2 3 4 5]
[5 2 1 1 1]
0


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values,counts=np.unique(y,return_counts=True)
print(values)
print(counts)
print(np.argmax(counts))

[1 2 3 4]
[3 2 3 2]
0


In [ ]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [ ]:
print(arr[0][1])
print(arr[2][0])

20
70


In [ ]:
VemulaManviSmaran = np.linspace(10, 100, 25)

print(f"Dimensions: {VemulaManviSmaran.ndim}")
print(f"Shape: {VemulaManviSmaran.shape}")
print(f"Total elements: {VemulaManviSmaran.size}")
print(f"Data type: {VemulaManviSmaran.dtype}")
print(f"Bytes consumed: {VemulaManviSmaran.nbytes}")
print("Array content:")
print(VemulaManviSmaran)

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Bytes consumed: 200
Array content:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
transposed_with_reshape = VemulaManviSmaran.reshape(-1, 1)
print("Transpose using reshape(-1, 1):")
print(transposed_with_reshape)
print(f"Shape after reshape: {transposed_with_reshape.shape}")

Transpose using reshape(-1, 1):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Shape after reshape: (25, 1)


In [ ]:
print("Transpose of reshaped array using .T attribute:")
print(transposed_with_reshape.T)
print(f"Shape of transposed array using .T: {transposed_with_reshape.T.shape}")

print("\n.T attribute on original 1-D array:")
print(VemulaManviSmaran.T)
print(f"Shape of original array using .T: {VemulaManviSmaran.T.shape}")

Transpose of reshaped array using .T attribute:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Shape of transposed array using .T: (1, 25)

.T attribute on original 1-D array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape of original array using .T: (25,)


In [ ]:
ucs420_VemulaManviSmaran = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_VemulaManviSmaran )
print(f"Shape: {ucs420_VemulaManviSmaran .shape}")

print(f"\nMean: {np.mean(ucs420_VemulaManviSmaran )}")
print(f"Median: {np.median(ucs420_VemulaManviSmaran )}")
print(f"Max: {np.max(ucs420_VemulaManviSmaran )}")
print(f"Min: {np.min(ucs420_VemulaManviSmaran )}")
print(f"Unique elements: {np.unique(ucs420_VemulaManviSmaran )}")

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Shape: (3, 4)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [ ]:
reshaped_ucs420_VemulaManviSmaran  = ucs420_VemulaManviSmaran .reshape(4, 3)

print("Reshaped Array (4 rows, 3 columns):")
print(reshaped_ucs420_VemulaManviSmaran )
print(f"Shape: {reshaped_ucs420_VemulaManviSmaran .shape}")

Reshaped Array (4 rows, 3 columns):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Shape: (4, 3)


In [ ]:
resized_ucs420_VemulaManviSmaran  = ucs420_VemulaManviSmaran .flatten()[:6].reshape(2, 3)

print("Resized Array (2 rows, 3 columns):")
print(resized_ucs420_VemulaManviSmaran )
print(f"Shape: {resized_ucs420_VemulaManviSmaran .shape}")

Resized Array (2 rows, 3 columns):
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
